name: KrishiVaidhya
description: Precision farming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.3
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.15.1
  firebase_database: ^10.2.3
  firebase_messaging: ^14.7.5
  fl_chart: ^0.63.0
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  flutter_form_builder: ^8.0.0
  formz: ^0.6.0
  getwidget: ^4.0.0
  geolocator: ^10.1.0
  google_sign_in: ^6.1.5
  http: ^1.0.0
  intl: ^0.17.0
  page_transition: ^2.0.9
  pedantic: ^1.11.1
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  flutter_clean_calendar: ^1.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model.tflite
    - assets/dict.txt
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular-webfont.ttf
